### PR TITLE
feat : Dialects MySQL string fuction 

### PR DESCRIPTION
**Pull request by vicheanath**
Added: dailects mysql string function #160

- [x] [ASCII()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ascii)	Return numeric value of left-most character
- [x] [BIN()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bin)	Return a string containing binary representation of a number
- [x] [BIT_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bit-length)	Return length of argument in bits
- [x] [CHAR()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_char)	Return the character for each integer passed
- [x] [CHAR_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_char-length)	Return number of characters in argument
- [x] [CHARACTER_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_character-length)	Synonym for CHAR_LENGTH()
- [x] [CONCAT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat)	Return concatenated string
- [x] [CONCAT_WS()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat-ws)	Return concatenate with separator
- [x] [ELT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_elt)	Return string at index number
- [x] [EXPORT_SET()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_export-set)	Return a string such that for every bit set in the value bits, you get an on string and for every unset bit, you get an off string
- [x] [FIELD()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field)	Index (position) of first argument in subsequent arguments
- [x] [FIND_IN_SET()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_find-in-set)	Index (position) of first argument within second argument
- [x] [FORMAT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_format)	Return a number formatted to specified number of decimal places
- [x] [FROM_BASE64()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_from-base64)	Decode base64 encoded string and return result
- [x] [HEX()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_hex)	Hexadecimal representation of decimal or string value
- [x] [INSERT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_insert)	Insert substring at specified position up to specified number of characters
- [x] [INSTR()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_instr)	Return the index of the first occurrence of substring
- [x] [LCASE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_lcase)	Synonym for LOWER()
- [x] [LEFT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_left)	Return the leftmost number of characters as specified
- [x] [LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_length)	Return the length of a string in bytes
- [ ] [LIKE](https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_like)	Simple pattern matching
- [x] [LOAD_FILE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_load-file)	Load the named file
- [x] [LOCATE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_locate)	Return the position of the first occurrence of substring
- [x] [LOWER()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_lower)	Return the argument in lowercase
- [x] [LPAD()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_lpad)	Return the string argument, left-padded with the specified string
- [x] [LTRIM()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ltrim)	Remove leading spaces
- [x] [MAKE_SET()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_make-set)	Return a set of comma-separated strings that have the corresponding bit in bits set
- [ ] [MATCH()](https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html#function_match)	Perform full-text search
- [x] [MID()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_mid)	Return a substring starting from the specified position
- [ ] [NOT LIKE](https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_not-like)	Negation of simple pattern matching
- [ ] [NOT REGEXP](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_not-regexp)	Negation of REGEXP
- [x] [OCT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_oct)	Return a string containing octal representation of a number
- [x] [OCTET_LENGTH()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_octet-length)	Synonym for LENGTH()
- [x] [ORD()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ord)	Return character code for leftmost character of the argument
- [x] [POSITION()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_position)	Synonym for LOCATE()
- [x] [QUOTE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_quote)	Escape the argument for use in an SQL statement
- [ ] [REGEXP](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp)	Whether string matches regular expression
- [ ] [REGEXP_INSTR()](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-instr)	Starting index of substring matching regular expression
- [ ] [REGEXP_LIKE()](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-like)	Whether string matches regular expression
- [ ] [REGEXP_REPLACE()](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-replace)	Replace substrings matching regular expression
- [ ] [REGEXP_SUBSTR()](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-substr)	Return substring matching regular expression
- [x] [REPEAT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_repeat)	Repeat a string the specified number of times
- [x] [REPLACE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_replace)	Replace occurrences of a specified string
- [x] [REVERSE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_reverse)	Reverse the characters in a string
- [x] [RIGHT()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_right)	Return the specified rightmost number of characters
- [ ] [RLIKE](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp)	Whether string matches regular expression
- [x] [RPAD()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_rpad)	Append string the specified number of times
- [x] [RTRIM()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_rtrim)	Remove trailing spaces
- [x] [SOUNDEX()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_soundex)	Return a soundex string
- [ ] [SOUNDS LIKE](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#operator_sounds-like)	Compare sounds
- [x] [SPACE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_space)	Return a string of the specified number of spaces
- [ ] [STRCMP()](https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#function_strcmp)	Compare two strings
- [x] [SUBSTR()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substr)	Return the substring as specified
- [x] [SUBSTRING()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring)	Return the substring as specified
- [x] [SUBSTRING_INDEX()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index)	Return a substring from a string before the specified number of occurrences of the delimiter
- [x] [TO_BASE64()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_to-base64)	Return the argument converted to a base-64 string
- [ ] [TRIM()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim)	Remove leading and trailing spaces
- [ ] [UCASE()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_ucase)	Synonym for UPPER()
- [ ] [UNHEX()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_unhex)	Return a string containing hex representation of a number
- [ ] [UPPER()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_upper)	Convert to uppercase
- [ ] [WEIGHT_STRING()](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_weight-string)	Return the weight string for a string

### CODE REVIEW

**Comment by vicheanath** [comment]
I have checked and tested it all check function is already in PR

**Comment by vicheanath** [comment]
for `CHAR()` i think i have problem about dialects script it can't extract this `[CHAR(N,... [USING charset_name])]`.

**Comment by invisal** [comment]
> for `CHAR()` i think i have problem about dialects script it can't extract this `[CHAR(N,... [USING charset_name])]`.

Yes. It is okay. You can fill those information first. I will check about the dialects problem that conflict with some of doc.

**Comment by invisal** [comment]
Let me know if it is all ready and I will do review and merge.

**Comment by vicheanath** [comment]
for some expressions that are not a function, it will not pop up document tools tip:
Screenshot 2023-10-08 at 10 08 27 AM

**It should be like this**

Screenshot 2023-10-08 at 10 10 54 AM

that is issue i will create only document, and we fixed them later

**Pull request merged**
